config/routes.rb
Rails.application.routes.draw do
  resources :reactions, only: [:create]
  resources :opinions

  #Manejador para mis comentarios y mis opiniones
  resources :articles do
    resources :reactions
    resources :opinions
  end

  devise_for :clients, controllers:{
    sessions: 'clients/sessions',
    registrations: 'clients/registrations'
  }

  #Manejador para mis entradas
  resources :clients do
    resources :opinions
    resources :articles
  end
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  post 'new_client_reaction', to: 'reactions#new_client_reaction', as: 'new_client_reaction'
  root 'articles#index'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :article
  belongs_to :client
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
    before_action only: [:edit, :update, :destroy] do
        authorize_request(["admin"])
      end
      
    def index
        @client = Client.find(params[:client_id])
        @opinions = @client.opinions
    end
    def create
        @article = Article.find(params[:opinion][:article_id])
        
        @opinion = Opinion.new(opinion_params)
        @opinion.client = current_client

        if client_signed_in?
            @opinion.client.id = current_client.id
        else
            @opinion.client_id = 2
        end

        respond_to do |format|
            if @opinion.save
                format.html { redirect_to article_path(@article.id), notice: 'Comment was successfully created.' }
            else
                format.html { redirect_to article_path(@article.id), notice: 'Comment was not created.' }
            end
        end
    end

    def destroy
        @article = Article.find(params[:article_id])
        @opinion = @article.opinions.find(params[:id])
        @opinion.destroy
        redirect_to article_path(@article), notice: 'Comment was successfully deleted.'
      end

    private

    def opinion_params
        params.require(:opinion).permit(:content, :article_id)
    end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_form.html.erb
<%= form_with(model: @opinion, local: true) do |f| %>

    <% if @opinion.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este comentario no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @opinion.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="row d-flex justify-content-center text-center">
        <div class="col-12">
            <%= f.hidden_field :article_id, value: @article.id %>
            <%= f.label :content, "Publica un comentario", class: "fs-3 fw-bold me-4" %>
            <%= f.text_area :content, size: "120x3", class: "form-control mt-3" %>
        </div>
        <div class="col-12"><%= f.submit "Comentar", class: "btn mybtn px-4 py-2 mt-3" %></div>
    </div>

    
<% end %>

app/views/opinions/_opinion.html.erb
<div id="<%= dom_id opinion %>">
    <div class="row">

        <div class="col-1 text-center"><%=image_tag opinion.client.photo, class: "mypfp rounded-circle" %></div>

        <div class="ms-1 col-10">
          <span class="fw-bold"><%= opinion.client.name%></span> <span class="fst-italic">Created <%= distance_of_time_in_words(opinion.created_at, Time.now, include_seconds: true)%> ago...</span> <br>
          <%= opinion.content %>
          <% if client_signed_in? && (current_client.role == 'admin') %>
            <p class="mt-1">
              <%= button_to article_opinion_path(article_id: opinion.article_id, id: opinion.id), method: :delete, class: "btn mybtn" do %>
              Eliminar comentario
            <% end %>        
            </p>
          <%end%>
        </div>
      </div>
</div>