config/routes.rb
Rails.application.routes.draw do
  resources :reactions, only: [:create]
  resources :opinions

  #Manejador para mis comentarios y mis opiniones
  resources :articles do
    resources :reactions
    resources :opinions
  end

  devise_for :clients, controllers:{
    sessions: 'clients/sessions',
    registrations: 'clients/registrations'
  }

  #Manejador para mis entradas
  resources :clients do
    resources :opinions
    resources :articles
  end
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  post 'new_client_reaction', to: 'reactions#new_client_reaction', as: 'new_client_reaction'
  root 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  Kinds = %w[like neutral dislike].freeze
  KindsSpanish = {"like" => "Me gusta", "neutral" => "Normal", "dislike" => "No me gusta"}.freeze

  
  belongs_to :client
  has_many :reactions, dependent: :destroy
  has_many :opinions, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action only: [:new, :create, :edit, :update, :destroy] do #Restriccion 1
    authorize_request(["author", "admin"])
  end

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @opinion = Opinion.new
  
    @article = Article.find(params[:id])
    @opinions = @article.opinions
    @reaction = Reaction.new
  
    if client_signed_in?
      @gatebutton = ""
      @active_kinds = Article::Kinds.select { |kind| @article.reactions.exists?(client: current_client, kind: kind) }
    else
      @gatebutton = "disabled"
      @active_kinds = []
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
    
  end

  # GET /articles/1/edit
  def edit
    
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    if client_signed_in?
      @article.client = current_client
    else
      @article.client_id = 2
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :picture, :description, :client_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def show_client_articles
        params[:client_id].present?
    end
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">

  <div class="row">
    <div class="col-12">
      <p class="fw-bold display-4 mb-5 text-center">
        <%= article.title %>
      </p>
      <p>
        <%= image_tag article.picture, class: "w-100 ps-5" %>
      </p>
      <p class="fs-5 text-center mt-5">
        <%= article.description %>
      </p>
      <p class="text-center">
        <span class="fw-bold">Por:</span>
        <span class="fst-italic"><%= article.client.name %></span>
      </p>

    </div>
  </div>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row d-flex justify-content-center mt-4">
    <div class="col-8">
      <div class="mb-3">
        <%= form.label :title, "Título", style: "display: block", class:"fw-bold mb-2" %>
        <%= form.text_field :title, class:"form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :picture, "Imagen adjunta", style: "display: block", class:"fw-bold mb-2" %>
        <%= form.text_field :picture, class:"form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :description, "Descripción de la foto", style: "display: block", class:"fw-bold mb-2" %>
        <%= form.text_area :description, size: "120x4", class:"form-control" %>
      </div>
      <div class="d-flex justify-content-end">
        <%= form.submit "Subir noticia", class:"btn mybtn fw-bold" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center">Editando publicación</h1>

<%= render "form", article: @article %>

<br>

<div class="row d-flex justify-content-center">
  <div class="col-8 text-end">
    <%= link_to "Ver publicación", @article, class: "btn mybtn mb-4" %> <br>
    <%= link_to "Volver", articles_path, class: "btn mybtn " %>
  </div>
</div>

app/views/articles/index.html.erb
<% if show_client_articles %>
<div id="articles">
  <% if client_signed_in? && (current_client.role == 'admin' || current_client.role == 'author') %>
  <div class="fs-5 btn mybtn py-2"><i class="fa-solid fa-circle-plus text-white"></i><%= link_to "Redactar entrada", new_article_path, class: "fw-bold ms-2 text-decoration-none text-white" %></div>
  <% if current_client.articles.count == 0 %>
    <p class="text-center">No hay entradas a tu nombre</p>
  <% end %>
<% end %>
  <% @articles.reverse.each do |article| %>
    <% if article.client_id == params[:client_id].to_i %>
      <div class="border my-5 px-5 py-4">
        <%= render article %>
        <p class="mb-0">
          <%= link_to "Ver entrada", article, class:"mt-4 btn mybtn" %>
        </p>
      </div>
    <% end %>
  <% end %>
<% else %>
<!-- ver los posts de todos los usuarios -->
    <p class="display-4 text-center">&#128049;Gatitos del día&#128049;</p>
    <hr class="mb-5 mt-4">
    <% if client_signed_in? && (current_client.role == 'admin' || current_client.role == 'author') %>
      <div class="fs-5 btn mybtn py-2"><i class="fa-solid fa-circle-plus text-white"></i><%= link_to "Redactar entrada", new_article_path, class: "fw-bold ms-2 text-decoration-none text-white" %></div>
      <% if @articles.count == 0 %>
        <p class="text-center">No hay entradas</p>
      <% end %>
    <% end %>
  <% @articles.reverse.each do |article| %>
    <div class="border my-5 px-5 py-4">
      <%= render article %>
      <p class="mb-0">
        <%= link_to "Ver entrada", article, class:"mt-4 btn mybtn" %>
      </p>
    </div>
  <% end %>
<% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Nuevo artículo</h1>

<%= render "form", article: @article %>

<div class="row d-flex justify-content-center mt-4 text-en">
  <div class="col-8 text-end"><%= link_to "Volver", articles_path, class:"btn mybtn" %></div>
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-9"><%= render @article %></div>
  
  <div class="col-3 d-flex justify-content-center">
    <% emojis = ["&#128571;", "&#128008;", "&#128574;"] %>
    <div class="w-75">
      <% Article::Kinds.zip(emojis).each do |kind, emoji| %>
        <% reaction_count = @article.reactions.where(kind: kind).count %>
        <% active_class = @active_kinds.include?(kind) ? "active" : "" %>
        <%= button_to "#{emoji} #{Article::KindsSpanish[kind]} (#{reaction_count})".html_safe, new_client_reaction_path(reaction: { article_id: @article.id, kind: kind }), method: :post, class: "btn btn-outline-dark #{active_class} #{@gatebutton} w-100 text-start py-2 mb-2" %>
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-9">
    <div class="d-flex justify-content-center">
      <%if client_signed_in?%>
      <%if current_client.id == @article.client_id || current_client.role == 'admin' %><br> <!--Solo el autor puede editar sus publicaciones ahora-->
        <%= link_to "Editar entrada", edit_article_path(@article), class: "btn btn-light mybtn text-white mt-3 mx-4" %>
        <%= button_to "Eliminar entrada", @article, method: :delete, class: "btn btn-light mybtn text-white mt-3" %>
      <%end%>
      <%end%>
    </div>

    <hr class="my-5">
    <%= render 'opinions/form' %>

    <div class="my-4">
      <% @opinions.reverse.each do |opinion| %>
        <div class="mb-3"><%= render partial: "opinions/opinion", locals: { opinion: opinion } %></div>
      <% end %>
    </div>
  </div>
</div>