config/routes.rb
Rails.application.routes.draw do
  resources :reactions, only: [:create]
  resources :opinions

  #Manejador para mis comentarios y mis opiniones
  resources :articles do
    resources :reactions
    resources :opinions
  end

  devise_for :clients, controllers:{
    sessions: 'clients/sessions',
    registrations: 'clients/registrations'
  }

  #Manejador para mis entradas
  resources :clients do
    resources :opinions
    resources :articles
  end
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  post 'new_client_reaction', to: 'reactions#new_client_reaction', as: 'new_client_reaction'
  root 'articles#index'
end

app/views/mycomponents/_mynavbar.html.erb
<div class="user-reverlator pt-3 pe-3 text-end">
    <% if client_signed_in? %>
      <span class="text-white"><span class="fw-bold">Sesión iniciada como:</span> <%=current_client.name%></span> <br>
      <span class="text-white"><span class="fw-bold">Rol:</span> <%=current_client.role.to_s%></span>
    <%else%>
    <span class="text-white"><span class="fw-bold">Usuario:</span> <%=Client.find(2).role.to_s%></span>
    <%end%>
  </div>
  <div class="w-100 d-flex justify-content-center bg-info">
      <%= image_tag 'logo.png', class: "mylogo text-center py-5" %>
  </div>
  <nav class="navbar navbar-expand-lg mynav p-0">
      <div class="container-fluid mx-5">
        <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Inicio", root_path, class: "nav-link fw-bold text-white px-4 py-3 mylinks" %>
              <% if client_signed_in? %>
                  <%= link_to edit_client_registration_path, class: "nav-link fw-bold text-white px-4 py-3 mylinks" do%>
                  <span>Mi cuenta</span>
                  <%end%> <!--current_user.name-->
                  <%= link_to 'Mis entradas', client_articles_path(current_client), class: "nav-link fw-bold text-white px-4 py-3 mylinks" %>
                  <%= link_to "Salir", destroy_client_session_path, class: "nav-link fw-bold text-white px-4 py-3 mylinks" %>
              <%else%>
                  <%= link_to "Entrar", new_client_session_path, class: "nav-link fw-bold text-white px-4 py-3 mylinks" %>
                  <%= link_to "Registrarse", new_client_registration_path, class: "nav-link fw-bold text-white px-4 py-3 mylinks" %>
              <%end%>
          </div>
        </div>
      </div>
    </nav>